---
# tasks file for nginx
- name: "Enable nginx repo"
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  when: nginx_yum_repo_enabled
  tags: nginx

- name: "Ensure a list of nginx related packages are installed"
  yum:
    name: "{{ packages }}"
  vars:
     packages:
     - openssl
     - nginx
     state: latest
  tags: nginx

- name: "Generate an OpenSSL private key with the default values (4096 bits, RSA)"
  openssl_privatekey:
    path: "{{ server_pem }}"
  tags: nginx, ssl

- name: "Generate an OpenSSL Certificate Signing Request"
  openssl_csr:
    path: "{{ server_csr }}"
    privatekey_path: "{{ server_pem }}"
    common_name: "{{ corpdomain }}"
  tags: nginx, ssl

- name: "Generate a Self Signed OpenSSL certificate"
  openssl_certificate:
    path: "{{ server_crt }}"
    privatekey_path: "{{ server_pem }}"
    csr_path: "{{ server_csr }}"
    provider: selfsigned
  tags: nginx, ssl

- name: "Copy certificate to ansible-master"
  fetch:
    src: "{{ server_crt }}"
    dest: "/etc/ssl/certs/{{ cert_filename }}"
    flat: yes
  tags: nginx, ssl

- name:  "Nginx blacklist creation"
  copy:
    src: "{{ role_path }}/files/blacklist.conf"
    dest: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0644
  tags: nginx

- name: "Add server Vhost templates"
  template:
    src: zabbix.conf.j2
    dest: "{{ confd }}/zabbix.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
  - { name: "zabbix", server1: "{{ groups['balancer'][0] }}", port: "{{ zabbix_port }}" }
  tags: nginx

- name: "Enable and start nginx"
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags: nginx

...
