---
# defaults file for pg
pguser: postgres
pggroup: postgres
pgdata: "/var/lib/pgsql/15/data"
repo_postgres: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
pgbin: "/usr/pgsql-15/bin/postgresql-15-setup"
pgcluster_reset: false
pgsql_cluster: false