---
# file master.yml

- name: "Setup project"
  hosts: all
  tasks:
    - name: "Display hostnames of Local network"
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"

- name: "Setup Rocky9 virtual machines."
  hosts: rocky
  tasks:
    - name: "Show Rocky hosts"
      debug:
        msg: "The Rocky hosts is {{ ansible_hostname }}"

    - name: "Run Rocky role"
      import_role:
        name: rocky_start

- name: "Setup postgres nodes"
  hosts: db
  gather_facts: yes
  vars_files:
  - ./group_vars/credentials
  tasks:
    - name: "Run the pg role"
      import_role:
        name: pg

- name: "Setup Metis dev enviroment."  
  hosts: metis
  gather_facts: yes
  vars_files:
  - ./group_vars/credentials
  tasks:
    - name: "Run metis role"
      import_role:
        name: metis        

- name: "Setup Python"  
  hosts: python
  gather_facts: no
  tasks:
    - name: "Run python role"
      import_role:
        name: python

- name: "Setup Docker"  
  hosts: docker
  gather_facts: no
  tasks:
    - name: "Run docker role"
      import_role:
        name: docker

- name: "Setup Docker"  
  hosts: docker
  gather_facts: no
  tasks:
    - name: "Run docker role"
      import_role:
        name: docker

- name: "Setup FrontEnd  Tier | Nginx"  
  hosts: nginx
  gather_facts: yes
  tasks:
    - name: "Run nginx role"
      import_role:
        name: nginx

- name: "Setup Kubernetes master."  
  hosts: k8s
  gather_facts: no
  tasks:
    - name: "Run k8s role"
      import_role:
        name: k8s                            


