---
# tasks file for metis
- name: "PostgreSQL | Create database user."
  postgresql_user:
    db: postgres
    name: "{{ metis_database_user }}"
    password: "{{ metis_database_pass }}"
    encrypted: yes
  no_log: true
  become: true
  become_user: "{{ pguser }}"
  tags: metis

- name: "PostgreSQL | Create metis database"
  postgresql_db:
    name: "{{ metis_dbname }}"
    owner: "{{ metis_database_user }}"
  become: true
  become_user: "{{ pguser }}"
  tags: metis

- name: "PostgreSQL | Grant ALL privileges on database"
  postgresql_privs:
    db: "{{ metis_dbname }}"
    privs: ALL
    type: database
    role: "{{ metis_database_user }}"
  become: true
  become_user: "{{ pguser }}"
  tags: metis

- name: "Metis | Get dotnet install script."
  get_url:
    url: "{{ dotnet_url }}"
    dest: /tmp
    mode: '0744'
  when: (install_dotnet|bool)
  tags: metis

- name: "Metis | Install dotnet 6."
  command:
    cmd: "/tmp/dotnet-install.sh -c 6.0"
  register: output_dotnet
  when: (install_dotnet|bool)
  tags: metis

- name: "Metis | Logging dotnet install actions."
  debug:
    var: output_dotnet
  when: (install_dotnet|bool)
  tags: metis

- name: "Metis | Add dotnet variable to bashrc."
  lineinfile:
    path: "~/.bashrc"
    regexp: "^ "
    line: "export PATH=$PATH:~/.dotnet/"
  become: true
  when: (install_dotnet|bool)
  tags: metis

- name: "Metis | Get nodejs install script."
  get_url:
    url: "{{ nodejs_url }}"
    dest: /tmp
    mode: '0744'
  when: (install_nodejs|bool)
  tags: metis

- name: "Metis | Install nodejs 18."
  command:
    cmd: "/tmp/setup_18.x"
  register: output_nodejs
  when: (install_nodejs|bool)
  tags: metis

- name: "Metis | Logging nodejs install actions."
  debug:
    var: output_nodejs
  when: (install_nodejs|bool)
  tags: metis

- name: "Metis | Install yarn repo package"
  get_url:
    url: "{{ yarn_repo }}"
    dest: /etc/yum.repos.d
    mode: '0644'
  when: (install_nodejs|bool)    
  tags: metis

- name: "Metis | Ensure a list of packages installed"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
    - nodejs
    - yarn
    state: present
  when: (install_nodejs|bool)    
  tags: metis

