---
# tasks file for docker
#Docker section
 
- name: "Docker | Remove old versions"
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest 
    - docker-latest-logrotate 
    - docker-logrotate 
    - docker-engine
  tags: docker 

- name: "Docker | Add docker repository."
  shell: 
    cmd: "yum-config-manager --add-repo={{ repo_docker }}"
  args:
    creates: /etc/yum.repos.d/docker
  tags: docker

- name: "Docker | Install packages."
  yum: 
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli 
    - containerd.io
    - docker-compose-plugin
    state: latest
  tags: docker 

- name: "Docker | Start and enable docker daemon via systemd."
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: "Docker | Add Docker user to admin group."
  user:
    name: docker
    groups: wheel
    append: yes
    state: present
    createhome: no
  tags: docker